# coding: utf-8

"""
    Kloudio APIs

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 0.1.BETA
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import kloud
from api.register_api import RegisterApi  # noqa: E501
from kloud.rest import ApiException


class TestRegisterApi(unittest.TestCase):
    """RegisterApi unit test stubs"""

    def setUp(self):
        self.api = api.register_api.RegisterApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_register_user(self):
        """Test case for register_user

        Register a user  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
