# coding: utf-8

"""
    Kloudio APIs

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: 0.1.BETA
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest
import datetime

import kloud
from kloud.models.job_dto import JobDto  # noqa: E501
from kloud.rest import ApiException

class TestJobDto(unittest.TestCase):
    """JobDto unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional):
        """Test JobDto
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # model = kloud.models.job_dto.JobDto()  # noqa: E501
        if include_optional :
            return JobDto(
                destination = 'email', 
                report_name = 'mysql-report', 
                report_id = '57d3273aed8c3e1e1c0d3746', 
                report_params = None, 
                frequency = 'Hourly', 
                am_pm = 'am', 
                hour = '01', 
                minute = '45', 
                day = 'Monday', 
                description = 'This is a sample query', 
                spreadsheet_id = '1-sl-_DtdBUmbi-FyJOwc2dXGd6xX0xZstX7UzlsU_EA', 
                sheet_id = '193832851', 
                sheet_name = 'Sales-v2', 
                timezone = 'PST', 
                select_cols = users, 
                tags = 'users', 
                email_on_success = True, 
                email_on_error = True, 
                metadata = None, 
                template_id = 'Y-z-jjFZ0H3u3maN', 
                template_name = 'Template2404a', 
                job_type = 'EMAIL'
            )
        else :
            return JobDto(
                destination = 'email',
                report_name = 'mysql-report',
                report_id = '57d3273aed8c3e1e1c0d3746',
                frequency = 'Hourly',
                am_pm = 'am',
                hour = '01',
                minute = '45',
                day = 'Monday',
        )

    def testJobDto(self):
        """Test JobDto"""
        inst_req_only = self.make_instance(include_optional=False)
        inst_req_and_optional = self.make_instance(include_optional=True)


if __name__ == '__main__':
    unittest.main()
