# coding: utf-8

"""
    Kloudio APIs

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 0.1.BETA
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import kloud
from models.connection_share_response import ConnectionShareResponse  # noqa: E501
from kloud.rest import ApiException


class TestConnectionShareResponse(unittest.TestCase):
    """ConnectionShareResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testConnectionShareResponse(self):
        """Test ConnectionShareResponse"""
        # FIXME: construct object with mandatory attributes with example values
        # model = kloud.models.connection_share_response.ConnectionShareResponse()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
