# coding: utf-8

"""
    Kloudio APIs

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: 0.1.BETA
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest
import datetime

import kloud
from kloud.models.connection_share_request import ConnectionShareRequest  # noqa: E501
from kloud.rest import ApiException

class TestConnectionShareRequest(unittest.TestCase):
    """ConnectionShareRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional):
        """Test ConnectionShareRequest
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # model = kloud.models.connection_share_request.ConnectionShareRequest()  # noqa: E501
        if include_optional :
            return ConnectionShareRequest(
                id = 87, 
                email = 'jags@kloud.io', 
                access = 'Can Use | Can Edit'
            )
        else :
            return ConnectionShareRequest(
                id = 87,
                email = 'jags@kloud.io',
                access = 'Can Use | Can Edit',
        )

    def testConnectionShareRequest(self):
        """Test ConnectionShareRequest"""
        inst_req_only = self.make_instance(include_optional=False)
        inst_req_and_optional = self.make_instance(include_optional=True)


if __name__ == '__main__':
    unittest.main()
