# coding: utf-8

"""
    Kloudio APIs

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: 0.1.BETA
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest
import datetime

import kloud
from kloud.models.connection_request import ConnectionRequest  # noqa: E501
from kloud.rest import ApiException

class TestConnectionRequest(unittest.TestCase):
    """ConnectionRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional):
        """Test ConnectionRequest
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # model = kloud.models.connection_request.ConnectionRequest()  # noqa: E501
        if include_optional :
            return ConnectionRequest(
                name = 'demo-connection', 
                host = 'localhost', 
                port = '1234', 
                database = 'users', 
                username = 'admin', 
                password = 'password', 
                db_type = 'SNOWFLAKE', 
                production = True, 
                ssl = True, 
                share_with = [], 
                enable_tunnel = True, 
                tunnel_info = None, 
                other_options = None, 
                fed = True, 
                dw = True, 
                metadata = '0', 
                connection_type = '0', 
                integration_user_id = 1.337, 
                web_type = '0', 
                ssl_info = None
            )
        else :
            return ConnectionRequest(
                name = 'demo-connection',
                host = 'localhost',
                port = '1234',
                database = 'users',
                username = 'admin',
                password = 'password',
        )

    def testConnectionRequest(self):
        """Test ConnectionRequest"""
        inst_req_only = self.make_instance(include_optional=False)
        inst_req_and_optional = self.make_instance(include_optional=True)


if __name__ == '__main__':
    unittest.main()
