# coding: utf-8

"""
    Kloudio APIs

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: 0.1.BETA
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest
import datetime

import kloud
from kloud.models.reports_request import ReportsRequest  # noqa: E501
from kloud.rest import ApiException

class TestReportsRequest(unittest.TestCase):
    """ReportsRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional):
        """Test ReportsRequest
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # model = kloud.models.reports_request.ReportsRequest()  # noqa: E501
        if include_optional :
            return ReportsRequest(
                name = 'mysql-report', 
                connection_id = 'LPdqQW-Kri0ZfU1a', 
                description = 'This is a sample query', 
                db_query = 'SELECT * FROM users;', 
                db_table = 'users', 
                sql_mode = True, 
                connection_type = 'DB', 
                _query_params = {}, 
                selected_cols = {}, 
                available_cols = {}, 
                shared_with = [], 
                db_schema = '0', 
                tags = ["finance","money"], 
                db_database = 'kloud', 
                joins = {}, 
                custom_join = '0', 
                additional_info = {}, 
                join_tables = {}, 
                settings = {}, 
                model = {}, 
                integration_id = 23
            )
        else :
            return ReportsRequest(
                name = 'mysql-report',
                connection_id = 'LPdqQW-Kri0ZfU1a',
        )

    def testReportsRequest(self):
        """Test ReportsRequest"""
        inst_req_only = self.make_instance(include_optional=False)
        inst_req_and_optional = self.make_instance(include_optional=True)


if __name__ == '__main__':
    unittest.main()
