# coding: utf-8

"""
    Kloudio APIs

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 0.1.BETA
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import kloud
from models.reports_request import ReportsRequest  # noqa: E501
from kloud.rest import ApiException


class TestReportsRequest(unittest.TestCase):
    """ReportsRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testReportsRequest(self):
        """Test ReportsRequest"""
        # FIXME: construct object with mandatory attributes with example values
        # model = kloud.models.reports_request.ReportsRequest()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
