# coding: utf-8

"""
    Kloudio APIs

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 0.1.BETA
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six


class ReportsRunRequest(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        '_query_params': 'list[str]',
        'preview_rows': 'float'
    }

    attribute_map = {
        '_query_params': 'queryParams',
        'preview_rows': 'previewRows'
    }

    def __init__(self, _query_params=None, preview_rows=None):  # noqa: E501
        """ReportsRunRequest - a model defined in Swagger"""  # noqa: E501
        self.__query_params = None
        self._preview_rows = None
        self.discriminator = None
        self._query_params = _query_params
        self.preview_rows = preview_rows

    @property
    def _query_params(self):
        """Gets the _query_params of this ReportsRunRequest.  # noqa: E501


        :return: The _query_params of this ReportsRunRequest.  # noqa: E501
        :rtype: list[str]
        """
        return self.__query_params

    @_query_params.setter
    def _query_params(self, _query_params):
        """Sets the _query_params of this ReportsRunRequest.


        :param _query_params: The _query_params of this ReportsRunRequest.  # noqa: E501
        :type: list[str]
        """
        if _query_params is None:
            raise ValueError("Invalid value for `_query_params`, must not be `None`")  # noqa: E501

        self.__query_params = _query_params

    @property
    def preview_rows(self):
        """Gets the preview_rows of this ReportsRunRequest.  # noqa: E501


        :return: The preview_rows of this ReportsRunRequest.  # noqa: E501
        :rtype: float
        """
        return self._preview_rows

    @preview_rows.setter
    def preview_rows(self, preview_rows):
        """Sets the preview_rows of this ReportsRunRequest.


        :param preview_rows: The preview_rows of this ReportsRunRequest.  # noqa: E501
        :type: float
        """
        if preview_rows is None:
            raise ValueError("Invalid value for `preview_rows`, must not be `None`")  # noqa: E501

        self._preview_rows = preview_rows

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(ReportsRunRequest, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, ReportsRunRequest):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
